### ISSUE TITLE
Titles are broken

### ISSUE THREAD

**Issue by flippyy** [LukeSmithxyz/lb#12]
I named a post "Test" and when I published the post, the title became "Test test test Test test"

I tried again, naming the post "Yee yee cowboys" and the title is just blank. 

I thought the issue might be that the text in the first post was "test" and in the second post it was "yee", so lb might not be handling duplicate text, but that is not the case. I tried a post called "l" with a text of "b" and the title became "Anime Should Be Illegal K-Pop Ought to be Illegal KPop Should be Illegal" (which are titles of previous posts I have made; don't ask)

The only modification I've made to the software is adding a line to the head in each published file that is a link to a google font, but the issue persists without said line. I tried again with a vanilla lb script, and named a post "yeet" with a text of "yote" but the title comes out as "yeet yeet".

It seems completely random, to be honest.

**Comment by LukeSmithxyz** [comment]
Yeah there was a big error with titles that I think I fixed yesterday. Are you using a version since then?

**Comment by flippyy** [comment]
Update: I just noticed that lb is now using a file called .htaccess to store post names and such. None of the posts I have deleted are being removed from that file as well, and it seems to be mixing things up.

Here's the file, it's pretty wonky looking. https://pastebin.com/Wig903bF

**Comment by flippyy** [comment]
Oh, your reply didn't pop up until after I posted that. Yes, I just cloned the repo a few minutes ago.

**Comment by LukeSmithxyz** [comment]
I don't know why I can't get this right. Lol. I just pushed another fix of an obvious bug but I'm going to test it for a minute.

**Comment by flippyy** [comment]
Thanks, it's all working now. Keep up the good work; this script is great.
