### ISSUE TITLE
./lb: line 36: [directory shit]/test.html: Permission denied

### ISSUE THREAD

**Issue by Squiblers** [LukeSmithxyz/lb#2]
Okay, so I'm probably going to look like a total brainlet _(which I am,)_ but I really can't figure this out. I've tried messing with the script, keeping it as default, re-cloning, a lot of the logical stuff. The `2018.html` file has the correct comment for LB to theoretically work, but I constantly get that error when trying to run `./lb new`. Please go light on how stupid I am.

Hope that's enough info.

**Comment by LukeSmithxyz** [comment]
Well it sounds like you don't have permission to edit the directory in question. You should make sure that the folder and its contents belong to the user you are with `chown` or at least that you have editing privileges there.

**Comment by Squiblers** [comment]
I just checked to see if I own it, chown says that I do in fact own the directory. Same exact error, too. Just to be sure, though, the command I did was `sudo chown squibs ~/lb/blog/drafts/`. Running that with verbose mode says that it's retained by me, so I don't know what's up. Anything else I could try?

**Comment by Squiblers** [comment]
@wickdChromosome Yeah I tried that, same error still.

**Comment by LukeSmithxyz** [comment]
Oh you know what I think it is, that line, line 36 calls your `$EDITOR` to open the draft file, so if you don't have an `$EDITOR` set, it will appear as blank and thus try to run your blog file as a command.

It's good form to always make sure you have the `$EDITOR` value set to your preferred text editor (e.g. vim) on your systems, as a lot of scripts, including this one use it. Look up how to do that permanently and then log back in and try running it again.

If you don't want to do that, you can go into the script and change `$EDITOR` to `vim` or whatever editor you like manually and not have to worry about it.

Tell me if that works.

**Comment by Squiblers** [comment]
@LukeSmithxyz That fixed it, thank you so much! Thank you @wickdChromosome as well for your help. Closing the issue now.
