### ISSUE TITLE
"Recent Blog Posts" feature missing?

### ISSUE THREAD

**Issue by lukerb52** [LukeSmithxyz/lb#31]
In the html for [lukesmith.xyz](lukesmith.xyz), there is a `<!--BLOG-->` tag, and under it are your 5 recent blog posts. Is `lb` supposed to put blog titles there. or is that managed by a different process? If it is managed by `lb`, then putting  in my html file and creating a new blogpost does not do the trick.

**Comment by LukeSmithxyz** [comment]
This isn't a feature of this repository, but a single command I have run when I upload my website which reads the output of this program. Here is what mine looks line if you need it explained specifically.

```
repl=$(grep "<li>" "$HOME/.local/src/website/blogindex.html" | sed 5q | tr -d '\n' | sed 's/[\/&]/\\&/g')
sed -i "s/<!--BLOG-->.*/<!--BLOG-->$repl/g" ~/.local/src/website/index.html
```

**Comment by lukerb52** [comment]
Thanks! I'll give it a look later.

**Comment by tallguyjenks** [comment]
@lukerb52 here's [luke's video on this](https://youtu.be/S1WQlr42xDM?t=588)
