### ISSUE TITLE
Titles with `/` fail to create standalone entries

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/lb#8]
Noting this here because I can't deal with it right now.

I noticed that while titles with `/` work with the RSS feed, rolling blog, etc., they do not properly output to the `blog/` folder as standalone entries.

It's a problem with sed, the `/` should be escaped. I'll fix this elegantly when I get the chance, but if anyone else wants to do a PR first, you're welcome to.

**Comment by MichaelTd** [comment]
You can experiment with sed's field separator,  when you are dealing with paths (lots of '/'), it's a good idea to use a different character (eg '|'?).

**Comment by MichaelTd** [comment]
You can experiment with sed's field separator, it could be any one character given that it's escaped in the expressions themselves, when you are dealing with paths (lots of '/'), it's a good idea to use a different character (eg '|'?).
